AllowedHosts: "*"

DynamoDB:
  Enabled: false

Serilog:
  Using:
    - Serilog.Sinks.Console
    - Serilog.Sinks.File
  MinimumLevel:
    Default: Information
    Override:
      Microsoft: Information
      Microsoft.AspNetCore: Information
      Microsoft.Extensions.Hosting: Warning 
      System: Warning
      SudokuSolutionEngine.API: Debug
  WriteTo:
    - Name: Console
      Args:
        outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}"
    - Name: File
      Args:
        path: "logs/sudoku-api-.log"
        rollingInterval: Day
        retainedFileCountLimit: 7
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}"
  Enrich:
    - FromLogContext
