Host: localhost
Port: 5000

DynamoDB:
  Enabled: true
  ServiceURL: http://localhost:4566
  TableName: SudokuSolutions
  TTL:
    Enabled: true
    Duration: 00:00:30

Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Information
      Microsoft.AspNetCore: Information
      Microsoft.Extensions.Hosting: Warning 
      System: Warning
      SudokuSolutionEngine.API: Debug
  WriteTo:
    - Name: Console
      # Args:
      #   outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}"